use_frameworks!

platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Aliffter/LXPodSpec.git'
target 'UserCenterModule_Example' do
  pod 'UserCenterModule', :path => '../'
  
  
  target 'UserCenterModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
